

version: "1.0"
stages:
  - "checkout"
  - "build"
steps:
  checkout:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: "${{CF_REVISION}}"
    stage: "checkout"
  build:
    title: Running docker image
    type: freestyle
    working_directory: '${{CF_REPO_NAME}}'
    arguments:
      image: 'centos8'
      commands:
