version: '1.0'
stages:
- checkout
- build
steps:
  clone:
    title: Cloning main repository...
    type: git-clone
    stage: checkout
    repo: 'codefreshdemo/cf-example-build-and-push'
    revision: 'master'
    git: github
  build_my_app:
    title: Building Node.Js Docker Image
    type: build
    stage: build
    image_name: my-node-js-app
    working_directory: {{clone}}
    tag: 'master'
    dockerfile: Dockerfile
